image: node:16.17.0

pages:
  stage: deploy
  before_script:
    - npm install
  script:
    - npm run build
    - cp -r build public
  artifacts:
    paths:
      - build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
